# -*- coding: utf-8 -*-
"""Task05Prodigy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PTgf5rcR7fysKEner-guyoQYYZCw5GSq
"""

!mkdir scraper
!pip install beautifulsoup4
!pip install requests
!pip install pandas

import requests
from bs4 import BeautifulSoup
import pandas as pd

baseurl = "https://www.thewhiskyexchange.com"
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.82 Safari/537.36'
}

k = requests.get(baseurl + '/c/35/japanese-whisky').text
soup = BeautifulSoup(k, 'html.parser')
productlist = soup.find_all("li", {"class": "product-grid__item"})

for product in productlist:
    product_url = baseurl + product.find('a')['href']
    # Extract product details (e.g., name, price, rating)
    # Store the data in a Pandas DataFrame or directly write to a CSV file.

data = {
    'Product Name': [],  # Add product names
    'Price': [],         # Add product prices
    'Rating': []         # Add product ratings
}
df = pd.DataFrame(data)

# Extract product details and populate the DataFrame
for product in productlist:
    product_name = product.find('h3', {'class': 'product-card__name'}).text.strip()
    product_price = product.find('p', {'class': 'product-card__price'}).text.strip()
    product_rating = product.find('span', {'class': 'review-overview__rating'}).text.strip()

    df = df.append({
        'Product Name': product_name,
        'Price': product_price,
        'Rating': product_rating
    }, ignore_index=True)

df.to_csv('whisky_products.csv', index=False)

